# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NativeScript Developer Day
email: sebastian.witalec@progress.com
description: >- # this means to ignore newlines until "baseurl:"
  NativeScript Developer Day is a community-focused event sponsored by Progress Software to discuss
  all things related to JavaScript and mobility including topics like mobile web development,
  mobile development, the Internet of Things, serverless and artificial intelligence.
short_description: >-
  NativeScript Developer Day is an event focused on JavaScript and mobility including topics like mobile web dev, mobile app dev, IoT, serverless and AI.
keywords: event,conference,javascript,js,mobile web development,mobile app development,mobile web dev,mobile app dev,serverless,IoT,internet of things,artificial intelligence,AI,virtual reality,VR,boston
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://NativeScriptDevDay.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: telerik
github_username:  telerik

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
